import data from "../../data.json";

// export const navRoutes = () => {
//   return data.nav || [];
// };

export const navRoutes = [
  {
    id: 0,
    title: "Home",
    path: "/",
    side: "left",
  },
  {
    id: 1,
    title: "Overall",
    path: "/",
    side: "right",
  },
  {
    id: 2,
    title: "Professional",
    path: "/",
    side: "right",
  },
  {
    id: 3,
    title: "Personal",
    path: "/",
    side: "right",
  },
  {
    id: 4,
    title: "Skills",
    path: "/",
    side: "right",
  },
  {
    id: 5,
    title: "Technology",
    path: "/",
    side: "right",
  },
  {
    id: 6,
    title: "Contact",
    path: "/",
    side: "right",
  },
];

export const zIndex = {
  header: 3,
  sideBar: 2,
  content: 0,
  footer: 3,
};

export const parallaxImages = [
  {
    id: 1,
    image: "BG1-Sky-3.1.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 2,
    image: "BG1-Moon-1.1.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 3,
    image: "BG1-MMB-1.3.png",
    show: true,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 4,
    image: "BG1-MMF-1.png",
    show: true,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 5,
    image: "BG1-LMB-1.3.png",
    show: true,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 6,
    image: "BG1-LMF-1.1.png",
    show: true,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 7,
    image: "BG1-RMB-1.1.png",
    show: true,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 8,
    image: "BG1-RMF-2.1.png",
    show: true,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 9,
    image: "BG1-Lake-1.1.png",
    show: true,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 10,
    image: "BG1-Lake-ForeGround-1.1.png",
    show: true,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 11,
    image: "BG1-Moon-s-1.1.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 12,
    image: "BG1-Sky-2.1.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 13,
    image: "BG2-Moon-2.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 14,
    image: "BG-2-Moon-Ref.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 15,
    image: "BG2-MountainRange.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 16,
    image: "BG2-Mountain-Trees.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 17,
    image: "BG2-RiverBank.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 18,
    image: "BG3-FRGF-1.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
  {
    id: 19,
    image: "BG3-FRG-Full-2.png",
    show: false,
    xSpeed: 0,
    ySpeed: 0,
    zSpeed: 0,
    xRotation: 0,
    yRotation: 0,
    zRotation: 0,
    xInitial: 0,
    yInitial: 0,
    zInitial: 0,
    xPos: 0,
    yPos: 0,
    zPos: 0,
  },
];

export const professional = [];
export const personal = [];
export const skills = [];
export const technologies = [];
export const projects = [];

export const socials = [
  {
    id: "0",
    title: "Discord",
    iconUrl: "discordBlack",
    url: "#",
  },
  {
    id: "1",
    title: "Twitter",
    iconUrl: "twitter",
    url: "#",
  },
  {
    id: "2",
    title: "Instagram",
    iconUrl: "instagram",
    url: "#",
  },
  {
    id: "3",
    title: "Telegram",
    iconUrl: "telegram",
    url: "#",
  },
  {
    id: "4",
    title: "Facebook",
    iconUrl: "facebook",
    url: "#",
  },
];

export const profileDetails = {
  name: "Tanmay Kumar Sarkar",
  contact: {
    phone: ["+91 9647160687", "+91 9749760920"],
    email: "tanmay.kr.sarkar@gmail.com",
    github: "https://github.com/tanmayKumarSarkar",
    address: "Kolkata, West Bengal, India",
  },
  profession: "Fullstack Software Developer",
  about_me_1: `Building Innovative, Robust and Scalable Digital Solutions`,
  about_me_2: `Experienced Full-Stack Developer with a passion for solving complex challenges and leading projects from concept to functional, scalable, and innovative software providing the best seamless digital experiences`,
  about_me_3: `
                Self-motivated Full-Stack Developer & Tech Lead from
                 India with over 8 years of experience in frontend and backend
                technologies. My passion for research, learning, and
                problem-solving drives me to create high-quality products.
              `,
  about_me_4: `
                I'm proficient in finding innovative business solutions and
                leading teams effectively providing the best project exprience.
              `,
  profile_summary: [
    "Having 8+ years of experience in Full- Stack Software Development, Architecture Design, IOT, DevOps & Web Development in the IT industry.",
    "Well acquainted with the Front- End technologies like ReactJS, React Native, Angular, JQuery.",
    "Well versed with Technology/ Platform: Java/ J2EE, .Net web application development and MVC architecture, Dynamics 365 CRM& App Components.",
    "Also, expertise in other Server- Side technologies like Node JS, Express, Django, GraphQL and Restful Web Service.",
    "Worked in both Relational (MySQL, Oracle, PostgreSQL) & Non- Relational (Mongo DB, ElasticSearch, Oracle NoSQL) Database& HarperDB.",
    "Communicating with internal/ external clients to identify specific requirements and expectations, managing client expectations as an indicator of quality.",
  ],
  experience: [
    {
      company: "Wipro",
      location: "Kolkata, India",
      duration: "Aug 2023 - Present",
      works: [
        {
          Project: "UnitedHealth Group Inc",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "React JS",
            "Svelte",
            "Node JS",
            "Handlebars JS",
            "Java",
            "Jenkins",
            "Openlens",
          ],
          Description:
            "Comprehensive Web Application for searching, comparing and shopping Medical Insurance Plans based on provided Zip Code and provided personal Information",
          Role: "Developer",
          Responsibilities: [
            "Front End Development",
            "Back End Development",
            "Integrated CD/ CI pipeline",
          ],
        },
      ],
    },
    {
      company: "Tech Mahindra",
      location: "Kolkata, India",
      duration: "Apr 2021 - Aug 2023",
      works: [
        {
          Project: "Microsoft Sustainability Info Hub",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "React JS",
            "Dynamics 365 CRM",
            "Microsoft Power Apps",
            "Power Automate",
            "Power BI",
            "Azure",
          ],
          Description:
            "Built and enhanced a D365 CRM application using Power Apps, aimed at capturing user requests and providing Sustainability data export capabilities in CSV format along with BI reporting.",
          Role: "Developer, Tech Lead",
          Responsibilities: ["Front End Development", "Back End Development"],
        },
        {
          Project: "Microsoft Teams's App Development",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "React JS",
            "Node JS",
            "Microsoft oAuth",
            "SSO",
            "Azure",
          ],
          Description:
            "Microsoft Teams App development using Node JS, React and Azure App Registration, Bot Services, Bot Framework on Meeting Extension, SSO, Adaptive Card etc.",
          Role: "Developer",
          Responsibilities: ["Front End Development", "Back End Development"],
        },
      ],
    },
    {
      company: "Ebiw Info Analytics Pvt. Ltd.",
      location: "Kolkata, India",
      duration: "Jan 2019 - Apr 2021",
      responsibilities: [],
      works: [
        {
          Project: "SMART-WELD IoT Solution",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "Angular 8",
            "NodeJS",
            "Bootstrap 4",
            "Power BI",
            "PostgreSQL",
            "Azure",
            "Git-Actions",
            "MQTT",
            "Data Pipeline",
          ],
          Description:
            "SmartWeld IoT Solution for Industrial Welding that involved sensor data collection through MQTT with Data Pipeline and real-time analytics.",
          Role: "Developer, Tech Lead",
          Responsibilities: [
            "SRS/ BRS",
            "Front End development",
            "Backend APIs development",
            "ETL Data Pipeline",
            "Real-time data visualization",
            "CD/ CI, Azure",
          ],
        },
        {
          Project: "YTY Gloves Manufacturer & AMDTF Data Analytics",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "Oracle",
            "Java",
            "Oracle Analytical Cloud",
            "Data Pipeline",
          ],
          Description:
            "Implemented a data collection and analytics pipeline for a gloves manufacturing company, leveraging Oracle Analytical Cloud (OAC) for business insights.",
          Role: "Developer, Data Engineer, Tech Lead",
          Responsibilities: [
            "SRS/ BRS",
            "Data Mapping",
            "ETL Data Pipeline",
            "BI Analytics",
            "Dashboards to track manufacturing KPIs",
          ],
        },
        {
          Project: "E-Trans - Driver Scorecard & Accident Prediction",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "React",
            "NodeJS",
            "Bootstrap",
            "Python (Django)",
            "Socket",
            "REST API",
            "PostgreSQL",
            "Power BI",
            "Data Pipeline",
          ],
          Description:
            "Developed a predictive analytics system for transportation safety, using real-time vehicle data to score driver performance and predict accidents.",
          Role: "Developer, Data Engineer, Tech Lead",
          Responsibilities: [
            "Front End development",
            "Backend APIs development",
            "ETL Data Pipeline",
            "BI Analytics",
            "Dashboards to monitor alerts & KPIs",
          ],
        },
        {
          Project: "PeekHire - Hiring Solutions",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "Angular 8",
            "jQuery",
            "Web RTC",
            "Bootstrap",
            "Java Spring Boot",
            "MongoDB",
          ],
          Description:
            "Interview Management System that can record and manage Audio/ Video/ Text in the absence of an interviewer with features for post-interview review & other features",
          Role: "Developer, Tech Lead",
          Responsibilities: [
            "SRS/ BRS",
            "Front End development",
            "Backend APIs development",
            "CD/ CI",
            "AWS",
          ],
        },
        {
          Project:
            "Oracle Industrial Data Model (OIDM) & NetSuite Implementation",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "Oracle Analytical Cloud (OAC)",
            "Oracle Industrial Data Model (OIDM)",
            "NetSuite",
          ],
          Description:
            "Worked on the development, migration, and implementation of Oracle Industrial Data Model and NetSuite for business data analytics.",
          Role: "Developer",
          Responsibilities: [
            "Backend APIs development",
            "Data Engineer",
            "Managed data migrations",
            "Analytics/ reporting",
          ],
        },
        {
          Project: "E-Trans - Real-Time Vehicle Tracking System",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "Raspberry Pi",
            "HarperDB",
            "Node.js",
            "Angular 4",
          ],
          Description:
            "Designed a system to track vehicles in real-time, identifying route deviations, idle times, and providing video feed recording.",
          Role: "Developer, Tech Lead",
          Responsibilities: [
            "SRS/ BRS",
            "Backend development",
            "UI for real-time monitoring",
          ],
        },
        {
          Project: "AEROMEXICO - Real-Time Airlines Baggage Tracking",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "Kafka",
            "Oracle NoSQL",
            "Hive",
            "Oracle DB",
            "Oracle Analytical Cloud (OAC)",
          ],
          Description:
            "Developed a baggage tracking system using RFID data to provide real-time analytics on baggage location and movement",
          Role: "Developer, Tech Lead",
          Responsibilities: [
            "Data Mapping",
            "ETL Data Pipeline",
            "Analytical dashboard reporting",
          ],
        },
        {
          Project: "CWP - Telecommunications Domain Analytics",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "ElasticSearch",
            "Logstash",
            "Kibana (ELK Stack)",
          ],
          Description:
            "Implemented real-time and historical CDR data analytics & reporting dashboard for telecommunications, focusing on recharge, usage, churn, and profit analysis",
          Role: "Developer",
          Responsibilities: [
            "Data Mapping",
            "ETL Data Pipeline",
            "BI Analytics",
          ],
        },
        {
          Project: "Smart Pump IoT Solutions",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "React",
            "jQuery",
            "Bootstrap",
            "Spring Boot",
            "React Native",
            "MongoDB",
            "Arduino",
            "GSM module",
            "Node JS",
          ],
          Description:
            "Smart pump system with Mobile App that can deliver an adequate amount of water depending on weather and soil texture",
          Role: "Developer, Tech Lead",
          Responsibilities: [
            "SRS/ BRS",
            "Front End development",
            "Backend APIs development",
            "Mobile App Development",
            "Hardware Assembly, Firmware Development",
          ],
        },
        {
          Project: "Real-Time Robotics Dashboard",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": ["ElasticSearch", "Logstash", "Kibana"],
          Description:
            "Developed a system to collect real-time data from working robots and display it on customizable dashboards accessible via any device.",
          Role: "Developer",
          Responsibilities: [
            "Data Mapping & Processing",
            "ETL Data Pipeline",
            "BI Analytics",
            "Real-time dashboard",
          ],
        },
      ],
    },
    {
      company: "Tata Consultancy Services",
      location: "Kolkata, India",
      duration: "August 2016 - Jan 2019",
      responsibilities: [],
      works: [
        {
          Project: "Project Management Portal",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": [
            "Microservices",
            "MySQL",
            "Hibernate",
            "Spring Boot",
            "Angular 4",
          ],
          Description:
            "Developed a comprehensive project management portal using microservices architecture to streamline project tracking and management processes.",
          Role: "Developer",
          Responsibilities: [
            "Designed architecture",
            "Backend services development",
            "User-friendly UI",
          ],
        },
        {
          Project: "Banking System Enhancement and Maintenance",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": ["J2EE", "MySQL", "Java 8"],
          Description:
            "Enhanced and maintained critical banking systems, focusing on fixing broken settlements and improving transactional support for equity, bonds, and stocks.",
          Role: "Developer",
          Responsibilities: [
            "Analyzed and resolved settlement issues",
            "Implemented system enhancements",
            "Seamless back-office support for institutional clients",
          ],
        },
        {
          Project: "SharePoint Development and Automation Testing",
          Duration: "Aug 2023 - Present",
          "Tools/Technologies": ["SharePoint Designer", "Selenium", "Sikuli"],
          Description:
            "Developed and designed workflows for content management on SharePoint, and conducted web and desktop application automation testing.",
          Role: "SharePoint Developer, Automation Tester",
          Responsibilities: [
            "Designed and developed SharePoint workflows",
            "Automation testing with Selenium and Sikuli for quality assurance of web and desktop applications",
          ],
        },
      ],
    },
  ],
  personal_projects: [
    {
      name: "Book Library Web Application",
      description: "Designed with GraphQL server.",
      technologies: ["Mongo DB", "GraphQL", "React JS"],
    },
    {
      name: "User Management and Video Player Web App",
      description:
        "Developed in Node, Express, MongoDB & Angular 4 as front end.",
      technologies: ["MEAN Stack"],
    },
    {
      name: "Recipe World Web Application",
      description:
        "Designed with data from RESTful external API, Color Game designed for Firefox OS with HTML/ CSS & Java Script.",
      technologies: ["React JS"],
    },
    {
      name: "Online Retail Banking System, MNREGA portal Web Application",
      description:
        "Developed in Java 1.8 with JSP, Servlet, Hibernate, Struts, JQuery & AJAX.",
      technologies: ["J2EE"],
    },
    {
      name: "E-Requisition System Web Application",
      description: "Developed in .NET 4.0 with ASP and JQuery, AJAX.",
      technologies: ["C# .NET/ Visual Studio"],
    },
    {
      name: "LAN Chat communication tool",
      description:
        "Developed using TCP/ IP and UDP protocol in C# implementation.",
      technologies: ["C# .NET/ Visual Studio"],
    },
    {
      name: "Running Ninja & Catch The Balls, Android Game",
      description:
        "Self-designed game character, character animations & C# as the Scripting language.",
      technologies: ["UNITY Game Engine"],
    },
    {
      name: "Auction System Desktop Application",
      description:
        "Developed in JAVA SWING (1.7) & Tic Tac Toe Android Game designed using Android Eclipse IDE.",
      technologies: ["JAVA SWING (1.7)"],
    },
    {
      name: "Stock Management System Web Application",
      description: "",
      technologies: ["Oracle 10g/ Oracle Forms"],
    },
    {
      name: "Online Examination System Web Application & Social Networking Site Web Application",
      description: "",
      technologies: ["PHP & MySQL"],
    },
  ],
  technical_skills: {
    languages: [
      "JAVA",
      "Java Script (ES6)",
      "PL/ SQL",
      "HTML",
      "CSS",
      "XML",
      "AJAX",
      "C#",
      "C",
      "C++",
      "MQL",
      "VB.Net",
      "JQuery",
      "PHP",
      "Python",
      "Typescript",
    ],
    technologies: [
      "React JS",
      "React Native",
      "Angular",
      "J2EE",
      "Web Service",
      "Node JS",
      "Express",
      "GraphQL",
      "Hibernate",
      "Spring",
      "Struts",
      "Django",
      "Web Socket",
      "Bootstrap",
      "ASP.Net",
      "Selenium & Sikuli Automation tools",
      "BI tools",
      "Kafka",
      "MQTT",
      "Logstash",
      "Kibana (ELK Stack)",
      "Azure",
      "D365 App Components",
    ],
    databases: [
      "PostgreSQL",
      "MySQL",
      "Oracle",
      "Mongo DB",
      "Elastic Search",
      "Harper DB",
    ],
    devops: [
      "GIT",
      "AWS (EC2, Route 53, CloudFront, Certificate Manager)",
      "Azure",
      "Jenkins",
      "GitHub Actions",
      "Tomcat",
      "Kubernetes",
      "Docker",
      "Azure Cloud Components",
    ],
    miscellaneous: [
      "Adobe After Effects",
      "Premiere Pro",
      "Flash/ Animate CC",
      "Illustrator",
      "Photoshop",
      "Dreamweaver",
      "Blender",
      "Autodesk Maya",
      "Sketch-Up",
      "InkScape",
      "UNITY Game Engine",
      "Visual Studio",
      "SharePoint Designer",
      "Eclipse",
      "MS Word",
      "MS Excel",
      "PowerPoint",
      "OAC",
      "Power BI",
      "Web Scraping",
    ],
    hardware: ["Raspberry Pi", "Arduino", "ESP8266 Node MCU", "GSM SIM900A"],
  },
  education: [
    {
      degree: "B.Tech. (INFORMATION TECHNOLOGY)",
      institution: "Jalpaiguri Govt. Engg. College",
      duration: "2012-2016",
      percentage: "83",
    },
    {
      degree: "Higher Secondary",
      institution: "Gobardanga Khantura High School",
      duration: "2011",
      percentage: "78",
    },
    {
      degree: "Secondary",
      institution: "Gobardanga Khantura High School",
      duration: "2009",
      percentage: "81.75",
    },
  ],
  personal_details: {
    dob: "",
    gender: "Male",
    languages: ["English", "Hindi", "Bengali"],
    address: "Kolkata, West Bengal, India",
  },
};

export const getRandomInt = (min, max) => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

export const getRandomIntV2 = (min1, max1, min2, max2) => {
  return Math.random() > 0.5
    ? getRandomInt(min1, max1)
    : getRandomInt(min2, max2);
};
